
ARDUINO_SENSOR_TYPE = "arduino"
SIMULATED_SENSOR_TYPE = "simulated"
AUTO_DETERMINE_SENSOR = "auto"

# TODO - put this as a CNAME and an SRV record in DNS instead
IN_PROCESS_DESTINATION = "local"
UDP_TRANSPORT_TYPE = "udp"
#DEFAULT_DESTINATION_PORT = "_sensors._udp"
#DEFAULT_DESTINATION_HOST = "192.168.56.1"
DEFAULT_DESTINATION_HOST = ""  # listen on all interfaces
DEFAULT_DESTINATION_PORT = 59999

DEFAULT_BAUD = 38400

ARDUINO_USB_VENDOR_ID = 8352
ARDUINO_USB_PRODUCT_ID = 16720

