
ARDUINO_SENSOR_TYPE="arduino"
SIMULATED_SENSOR_TYPE="simulated"
AUTO_DETERMINE_SENSOR="auto"

# TODO - put this as a CNAME and an SRV record in DNS instead
IN_PROCESS_DESTINATION="local"
UDP_TRANSPORT_TYPE="udp"
#DEFAULT_DESTINATION_PORT="_sensors._udp"
DEFAULT_DESTINATION_HOST="localhost"
DEFAULT_DESTINATION_PORT=59999

